[package]
name = "trains"
version = "0.1.0"
edition = "2021"

[dependencies]
freds = { version = "0.1", features = ["read", "write"] }
dialoguer = { version = "0.10", features = []}
async-trait = "0.1"
